name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev build-essential \
        git zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev \
        libreadline-dev libffi-dev libsqlite3-dev wget libjpeg-dev libfreetype6-dev
        pip install --user --upgrade pip
        pip install --user cython==0.29.36 buildozer

    - name: Build APK
      run: |
        ~/.local/bin/buildozer android debug
